version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  -
    id: "notecard-mcp-linux"
    dir: notecard
    binary: "notecard_{{ .Os }}-{{ .Arch }}"

    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64

  -
    id: "notehub-mcp-linux"
    dir: notehub
    binary: "notehub_{{ .Os }}-{{ .Arch }}"

    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64

  -
    id: "dev-mcp-linux"
    dir: dev
    binary: "dev_{{ .Os }}-{{ .Arch }}"

    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64

  -
    id: "notecard-mcp"
    dir: notecard
    binary: "notecard_{{ if eq .Os \"windows\" }}win32{{ else }}{{ .Os }}{{ end }}-{{ .Arch }}"

    env:
      - CGO_ENABLED=1
    goos:
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm
        goarm: 6
      - goos: windows
        goarch: arm64

  -
    id: "notehub-mcp"
    dir: notehub
    binary: "notehub_{{ if eq .Os \"windows\" }}win32{{ else }}{{ .Os }}{{ end }}-{{ .Arch }}"

    env:
      - CGO_ENABLED=1
    goos:
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm
        goarm: 6
      - goos: windows
        goarch: arm64

  -
    id: "dev-mcp"
    dir: dev
    binary: "dev_{{ if eq .Os \"windows\" }}win32{{ else }}{{ .Os }}{{ end }}-{{ .Arch }}"

    env:
      - CGO_ENABLED=1
    goos:
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm
        goarm: 6
      - goos: windows
        goarch: arm64

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
