name: Release Notecard and Notehub MCP servers

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Fetch all tags
        run: git fetch --force --tags
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      -
        name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      -
        name: Install DXT
        run: npm install -g @anthropic-ai/dxt
      -
        name: Install jq
        run: brew install jq
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release -f .goreleaser.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Generate platform-specific DXT files
        run: |
          chmod +x ./generate_platform_dxt.sh
          bash ./generate_platform_dxt.sh
      -
        name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: note-mcp
          path: dxt/*
